### ISSUE TITLE
"Hans Winkler" (https://mine.acdh-ch-dev.oeaw.ac.at/person/7033) is a mixture of two persons

### ISSUE THREAD

**Issue by ngoeth** [acdh-oeaw/apis-mine#189]
Hans Winkler, **kmi**, born 1945 is definitiv no "Diplomat, Jurist", but Zoologe (or Ornithologist)

Maybe this entry is mixed with Dr. Hans Winkler, also born 1945, but never Mitglied of ÖAW

After opening the details page (https://mine.acdh-ch-dev.oeaw.ac.at/person/7033) I get:

Hans Winkler as Director of KLIVV (that is correct); but at the same time linked with " Österreichisches Parlament [28371](https://www.parlament.gv.at/WWER/PAD_28371/) https://www.parlament.gv.at/person/2837", which definitely is incorrect. (Also the other "Online-ressources" are liked to the wrong Person.)

**Comment by sennierer** [comment]
Sandra to correct Metadata, Matthias to add correct identifiers
