### ISSUE TITLE
Institut für Schallforschung is sub-unit of Kuratorium?

### ISSUE THREAD

**Issue by ngoeth** [acdh-oeaw/apis-mine#190]
I am not sure, but I doubt that this is correct:

![grafik](https://github.com/acdh-oeaw/apis-mine/assets/167221554/13b7e41e-4149-46d0-80b6-9a00505b1710)

Can it be that an "Institute" is part of an "Kuratorium"

**Comment by saklos** [comment]
![grafik](https://github.com/acdh-oeaw/apis-mine/assets/122993318/bdc39744-7288-40b4-9355-3d1c50a22691)
