### ISSUE TITLE
Emil Weyr: date of birth wrong

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-mine#216]
born on 1.9.1948 and not as stated in MINE 31.8.1848: https://katalog.ahmp.cz/pragapublica/PaginatorMedia.action?_sourcePage=Jp0-uks4MVA28TiHteT0KAvC0R1l77D7HOF7MBpzVLj13nqWD7HCrbfLhtK1669hG2JzsqKk0GUXMHpeDMX0iyXt68IiiGrFFgUCZhUg8tM%3D&row=161

**Comment by saklos** [comment]
Surely 1848
