### ISSUE TITLE
detail page of persons is missing "Obmann/Obfrau" section

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-mine#99]

**Comment by richardhadden** [comment]
See http://localhost:8000/person/2879, Funktionen in die Akademie — should distinguish between mitglieder and Obmann/frau

**Comment by richardhadden** [comment]
Fixed by: https://github.com/acdh-oeaw/apis-mine/tree/rh/fix/99-differentiate-obmann-from-membership-in-detail-page
